services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mario-lgp-dev
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/gdm/Xauthority:/root/.Xauthority:ro
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
      - PYTHONUNBUFFERED=1
      - SDL_VIDEODRIVER=x11
    stdin_open: true
    tty: true
    # Necessário para permitir que o pygame exiba a janela gráfica
    network_mode: host
